import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#fff' },
  screen: { flex: 1 },
  header: {
    padding: 16,
    paddingTop: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  headerIcon: { fontSize: 22 },
  headerTitle: { fontSize: 16, fontWeight: '700', marginLeft: 8 },
  headerChevron: { color: '#888', marginLeft: 6 },
  langToggle: { color: '#007aff', fontWeight: '600' },

  sectionPadding: { paddingHorizontal: 16, paddingTop: 12 },
  deviceCard: {
    backgroundColor: '#f7f7f7',
    borderRadius: 12,
    padding: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  deviceAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#f2df0d',
    marginRight: 12,
  },
  deviceTitle: { fontWeight: '700', fontSize: 16 },
  deviceSubtitle: { color: '#666', marginTop: 2 },
  onlineDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#16a34a',
  },
  onlineText: { color: '#16a34a', marginLeft: 4 },
  addIcon: { fontSize: 24, color: '#666' },
  addLabel: { fontSize: 12, color: '#666' },

  infoCard: {
    backgroundColor: '#f7f7f7',
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: '#eee',
  },
  infoTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  infoSmall: { color: '#666', fontSize: 13 },
  infoTitle: { fontSize: 16, fontWeight: '700' },
  refreshIcon: { fontSize: 18, color: '#777' },
  convRow: { marginTop: 8 },
  convWho: { fontWeight: '700' },
  convText: { color: '#111' },
  convRowAlt: { marginTop: 8 },
  convTextAlt: { color: '#666' },
  viewReport: {
    marginTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#e6e6e6',
    paddingTop: 10,
    alignItems: 'center',
  },
  viewReportText: { color: '#666' },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  smallCard: {
    width: '48%',
    backgroundColor: '#f7f7f7',
    padding: 12,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  smallCardIcon: { fontSize: 22 },
  smallCardTitle: { fontWeight: '700' },
  smallCardSub: { color: '#666', fontSize: 12 },

  promoCard: {
    width: 260,
    borderRadius: 12,
    backgroundColor: '#f7f7f7',
    marginRight: 12,
    overflow: 'hidden',
  },
  promoImage: { width: '100%', height: 140, backgroundColor: '#ccc' },
  promoTitle: { fontWeight: '700' },
  promoSub: { color: '#666', fontSize: 13 },

  sectionTitle: { fontSize: 20, fontWeight: '700', paddingHorizontal: 16 },

  recommendItem: {
    width: 120,
    backgroundColor: '#f7f7f7',
    marginRight: 12,
    padding: 12,
    borderRadius: 12,
    alignItems: 'center',
  },
  recommendAvatar: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#ddd',
    marginBottom: 8,
  },
  recommendTitle: { fontWeight: '700' },
  recommendSub: { color: '#666', fontSize: 12, textAlign: 'center' },
  recentItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    backgroundColor: '#f7f7f7',
    borderRadius: 12,
    marginBottom: 8,
  },
  recentAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#ddd',
  },
  recentTitle: { fontWeight: '700' },
  recentSub: { color: '#666' },

  // utility styles
  scrollContent: { paddingBottom: 100 },
  rowCenter: { flexDirection: 'row', alignItems: 'center' },
  rowBetweenCenter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  mt6: { marginTop: 6 },
  mt12: { marginTop: 12 },
  mt20: { marginTop: 20 },
  pv8: { paddingVertical: 8 },
  recentContainer: { paddingHorizontal: 16, marginTop: 8, paddingBottom: 40 },
  smallPadding: { padding: 8 },
  alignCenter: { alignItems: 'center' },
  flex1: { flex: 1 },

  tabBarContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 64,
    backgroundColor: 'rgba(255,255,255,0.95)',
    borderTopWidth: 1,
    borderTopColor: '#eee',
    flexDirection: 'row',
  },
  tabItem: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  tabIcon: { fontSize: 20, color: '#777' },
  tabIconActive: { color: '#f2df0d' },
  tabLabel: { fontSize: 11, color: '#777', marginTop: 4 },
  tabLabelActive: { color: '#333', fontWeight: '700' },

  centerScreen: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  centerTitle: { fontSize: 20, fontWeight: '700' },
  centerSub: { color: '#666', marginTop: 8 },
});

export default styles;
